# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1291395532);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1291395717);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.download.dir", "/tmp");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.formfill.enable", false);
user_pref("browser.history_expire_days", 0);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.open.lastDir", "/home/ryan/projects/adblockplus");
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.13");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.adblockplus.clearStatsOnHistoryPurge", true);
user_pref("extensions.adblockplus.composer_default", 2);
user_pref("extensions.adblockplus.currentVersion", "1.3a");
user_pref("extensions.adblockplus.defaultstatusbaraction", 2);
user_pref("extensions.adblockplus.defaulttoolbaraction", 1);
user_pref("extensions.adblockplus.detachsidebar", false);
user_pref("extensions.adblockplus.enable_key", "");
user_pref("extensions.adblockplus.enabled", true);
user_pref("extensions.adblockplus.fastcollapse", false);
user_pref("extensions.adblockplus.flash_scrolltoitem", true);
user_pref("extensions.adblockplus.frameobjects", true);
user_pref("extensions.adblockplus.hideimagemanager", true);
user_pref("extensions.adblockplus.patternsbackupinterval", 24);
user_pref("extensions.adblockplus.patternsbackups", 5);
user_pref("extensions.adblockplus.patternsfile", "adblockplus/patterns.ini");
user_pref("extensions.adblockplus.previewimages", true);
user_pref("extensions.adblockplus.savestats", true);
user_pref("extensions.adblockplus.settings_key", "Accel Shift E");
user_pref("extensions.adblockplus.showinstatusbar", false);
user_pref("extensions.adblockplus.showintoolbar", true);
user_pref("extensions.adblockplus.sidebar_key", "Accel Shift V");
user_pref("extensions.adblockplus.subscriptions_fallbackerrors", 5);
user_pref("extensions.adblockplus.subscriptions_fallbackurl", "https://adblockplus.org/getSubscription?version=%VERSION%&url=%SUBSCRIPTION%&downloadURL=%URL%&error=%ERROR%&channelStatus=%CHANNELSTATUS%&responseStatus=%RESPONSESTATUS%");
user_pref("extensions.adblockplus.subscriptions_listurl", "https://adblockplus.org/subscriptions.xml");
user_pref("extensions.adblockplus.synchronizationinterval", 24);
user_pref("extensions.adblockplus.whitelistschemes", "about chrome file irc moz-safe-about news resource snews x-jsd addbook cid imap mailbox nntp pop data javascript moz-icon");
user_pref("extensions.enabledItems", "langpack-en-GB@firefox-3.6.ubuntu.com:3.6,{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}:1.3a,langpack-en-AU@firefox-3.6.ubuntu.com:3.6,langpack-en@firefox-3.6.ubuntu.com:3.6,langpack-en-CA@firefox-3.6.ubuntu.com:3.6,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.13");
user_pref("extensions.lastAppVersion", "3.6.13");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pref.privacy.disable_button.cookie_exceptions", false);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.passwords", true);
user_pref("privacy.clearOnShutdown.siteSettings", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("signon.rememberSignons", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1298070594);
