#!/usr/bin/ruby

require "commandline-options.rb"
require "load-data.rb"
require "scan.rb"
require "process-matches.rb"

options = parseOptions( ARGV )

Process.exit unless options

urls = getURLs( options )
scans = getScans( options )

if options.verbose then
  puts "this scan being performed for client: " + options.humanClient
  
  puts "selenium server host: " + options.seleniumHost
  puts "selenium server port: 4444"
  
  puts "repeating each url #{options.repeat} times"
  
  puts "urls scanned (found #{urls.length}):"
  urls.each { |url| puts " " + url }

  puts "competitors sought (found #{scans.length}):"
  scans.each { |scan| puts " " + scan }
end

if options.bail then
  puts "--bail invoked, terminating"
  Process.exit
end

scansWithMatch = runScan( urls, scans, options )

processMatches( scansWithMatch, options)



  






